version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-174-129-22-22.compute-1.amazonaws.com
            database: du0vj3q1tk848
            user: nhzxazoinwqhgd
            password: ca4d35f78f316d68ef89e41e9c69a574d1314ec28eda9c02690897a026a9655a
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true